sudo: required
services:
  - docker

before_install:
  - docker build -t abdulwahabameth/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abdulwahabameth/react-test npm test

after_success:
  - docker build -t abdulwahabameth/multi-client ./client
  - docker build -t abdulwahabameth/multi-nginx ./nginx
  - docker build -t abdulwahabameth/multi-server ./server
  - docker build -t abdulwahabameth/multi-worker ./worker
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push the images to docker hub
  - docker push abdulwahabameth/multi-client
  - docker push abdulwahabameth/multi-nginx
  - docker push abdulwahabameth/multi-server
  - docker push abdulwahabameth/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'me-south-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-me-south-1-382487711276'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
